# Generated by Django 4.1.7 on 2023-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='farzand',
            field=models.CharField(blank=True, help_text='nechi yosh atrofida', max_length=12, null=True, verbose_name='Farzandingiz yoshi'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='farzand_yoshi',
            field=models.IntegerField(help_text="frazandingiz yo'q bo'lsa iltimos 0 raqamini kiriting ", verbose_name='Farzandingiz yoshi'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='ish_faoliyat',
            field=models.CharField(blank=True, help_text='buyruq asosida, soatbay yoki ishsiz shulardan birini yozing', max_length=30, null=True, verbose_name='Ish faoliyatingiz'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='ish_manzil',
            field=models.CharField(blank=True, help_text="iltimos to'liq kiritng", max_length=200, null=True, verbose_name='Ish joyingiz manzili'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='ish_masofa',
            field=models.CharField(blank=True, help_text='uyingizdan ishingizgacha masofa', max_length=20, null=True, verbose_name='Ish joyingizgacha masofa'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='kredit_maqsad',
            field=models.CharField(blank=True, help_text='maqsadingiz haqida qisqacha', max_length=150, null=True, verbose_name='Kredit olishdan maqsadingiz'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='kredit_olish',
            field=models.CharField(blank=True, help_text="ha yoki yo'q", max_length=3, null=True, verbose_name='Kredit olishga ehtiyojingiz bormi'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='kredit_summa',
            field=models.FloatField(help_text="agra kredit olmoqchi bo'lmasangiz iltimos 0 sonini kiritng", verbose_name='Kredit miqdorini kiritng'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='lavozim',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ish joyingizdagi lavozimingiz'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='oila',
            field=models.CharField(blank=True, help_text='turmush qurgan yoki qurmagan', max_length=18, null=True, verbose_name='Oilaviy holati'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='oilaviy_biznes',
            field=models.CharField(blank=True, help_text="ha yoki yo'q", max_length=3, null=True, verbose_name='Oilaviz biznesga imkoniyatingiz bormi'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='oilaviy_biznes2',
            field=models.CharField(blank=True, help_text='dehqonchilik chorvachilik, ...', max_length=22, null=True, verbose_name="Qaysi biznes bilan shug'ullanmoqchisiz"),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='qaysi_tizimda_ishlash',
            field=models.CharField(blank=True, help_text="agar hozirda ishsiz bo'lsangiz kelajakda qaysi tizimda ishlamoqchisiz", max_length=120, null=True, verbose_name='Qaysi tizimda ishlamoqchisiz'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='xozirgi_ish',
            field=models.CharField(blank=True, help_text='ha yoki yoq', max_length=3, null=True, verbose_name='Xozirgi ishlaysizmi'),
        ),
    ]
