# Generated by Django 4.1.7 on 2023-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_talabalar_farzand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='biznes_izox',
            field=models.TextField(blank=True, help_text="to'liqroq va aniqroq", null=True, verbose_name='Biznes qilish borasida izoxlaringiz'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='qoshimcha_izoh',
            field=models.TextField(blank=True, help_text="to'liqroq va aniqroq", null=True, verbose_name='Ishlash borasida izoxingiz'),
        ),
    ]
